import os
import json
import argparse
import collections

SILOS = [
    ("reports/corpus.jsonl", "generated", None),
    ("reports/corpus_confident_wrong.jsonl", "generated", "confident_wrong"),
    ("realmath/reports/realmath_corpus.jsonl", "realmath", None),
]

BAND_LO, BAND_HI = 0.125, 0.875


def is_band(record):
    if record["failure_mode"] == "band":
        return True
    p = record["pass_at_k"]
    if p is None:
        return False
    try:
        return BAND_LO <= float(p) <= BAND_HI
    except (TypeError, ValueError):
        return False


def first(record, keys, default=""):
    for k in keys:
        v = record.get(k)
        if v not in (None, ""):
            return v
    return default


def normalise(record, source, default_mode):
    return {
        "source": source,
        "family": first(record, ["family", "tier"], "unknown"),
        "failure_mode": first(record, ["failure_mode", "label", "mode"], default_mode or "unknown"),
        "problem": first(record, ["prompt", "question", "problem"]),
        "answer": first(record, ["answer", "truth", "expected", "ground_truth",
                                  "target", "solution", "correct_answer", "ground"]),
        "pass_at_k": record.get("pass_at_k"),
        "committed_wrong": first(record, ["modal_wrong", "committed_wrong"], ""),
        "link": first(record, ["link"], ""),
    }


def load_silos(silos, root):
    out = []
    for rel, source, default_mode in silos:
        path = os.path.join(root, rel)
        if not os.path.exists(path):
            print(f"skip (missing): {rel}")
            continue
        n = 0
        for line in open(path):
            line = line.strip()
            if not line:
                continue
            out.append(normalise(json.loads(line), source, default_mode))
            n += 1
        print(f"loaded {n} from {rel}")
    return out


def write_jsonl(rows, path):
    with open(path, "w") as f:
        for i, r in enumerate(rows, 1):
            r = dict(r, id=i)
            f.write(json.dumps(r) + "\n")


def write_markdown(rows, path):
    groups = collections.OrderedDict()
    for r in rows:
        groups.setdefault((r["source"], r["failure_mode"]), []).append(r)

    lines = ["# Master corpus", ""]
    lines.append(f"All {len(rows)} labelled problems aggregated across silos, "
                 "human readable for review. Generated by `src/build_master_corpus.py`.")
    lines.append("")
    lines.append("| Source | Failure mode | Count |")
    lines.append("|--------|--------------|-------|")
    for (src, mode), items in groups.items():
        lines.append(f"| {src} | {mode} | {len(items)} |")
    lines.append("")

    idx = 0
    for (src, mode), items in groups.items():
        lines.append("---")
        lines.append(f"## {src} / {mode} ({len(items)})")
        lines.append("")
        for r in items:
            idx += 1
            p = r["pass_at_k"]
            pstr = "band" if p is None else f"{p:.2f}"
            head = f"### {idx}. {r['family']} (pass {pstr})"
            lines.append(head)
            if r["link"]:
                lines.append(f"`{r['link']}`")
            lines.append("Problem:")
            lines.append("```")
            lines.append(str(r["problem"]).strip() or "(no prompt recorded)")
            lines.append("```")
            lines.append(f"Answer: `{str(r['answer']).strip()}`")
            if r["committed_wrong"]:
                lines.append(f"Committed wrong: `{str(r['committed_wrong']).strip()}`")
            lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--jsonl", default="master_corpus.jsonl")
    ap.add_argument("--markdown", default="MASTER_CORPUS.md")
    ap.add_argument("--all-modes", action="store_true",
                    help="include every failure mode; default keeps band only")
    args = ap.parse_args()

    rows = load_silos(SILOS, args.root)
    if not args.all_modes:
        rows = [r for r in rows if is_band(r)]
        for r in rows:
            r["failure_mode"] = "band"
    rows.sort(key=lambda r: (r["source"], r["failure_mode"], r["family"]))

    write_jsonl(rows, os.path.join(args.root, args.jsonl))
    write_markdown(rows, os.path.join(args.root, args.markdown))

    by_source = collections.Counter(r["source"] for r in rows)
    by_mode = collections.Counter(r["failure_mode"] for r in rows)
    print(f"\nmaster corpus: {len(rows)} problems")
    print("by source:", dict(by_source))
    print("by failure mode:", dict(by_mode))
    print(f"wrote {args.jsonl} and {args.markdown}")


if __name__ == "__main__":
    main()
